version: 2.1 

 

jobs: 

  build-and-test:  

    machine: 

      image: ubuntu-2004:09202104-01 

        

    stepss: 

      - checkout 

      - run: make deps 

      - run: make test       

workflows: 

  basic:  

    jobs: 

      - build-and-test 